---
branch: master
repositoryUrl: https://github.com/peakfijn/docker.git
tagFormat: ${version}

analyzeCommits:
  path: '@semantic-release/commit-analyzer'
  preset: peakfijn
  releaseRules: release-rules-peakfijn

generateNotes:
  - path: '@semantic-release/release-notes-generator'
    preset: peakfijn

verifyConditions:
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - semantic-release-git-branches

prepare:
  - '@semantic-release/changelog'
  - path: '@semantic-release/npm'
    npmPublish: false
  - path: semantic-release-git-branches
    branchMerges: [develop, master]
    message: |-
      release: create new version ${nextRelease.version}

      ${nextRelease.notes}

publish:
  - '@semantic-release/github'
